name: infectSim
description: A discrete infection simulator. Guaranteed not to match real infection models.
version: 1.0.0
homepage: https://github.io/mjallison42/infectsim

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  normal: ^0.5.1
  modern_charts: ^0.1.19
  intl: ^0.16.1
